server:
  port: 8000

spring:
  application:
    name: redis
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #datasource:
  #  url: jdbc:mysql://localhost:3306/spring-security?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  #  username: root
  #  password: root
  #  driver-class-name: com.mysql.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver   #此处不对哈  mysql驱动包
    url: jdbc:mysql://localhost:3306/shangdj?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    cluster:
      nodes:
        #分片集群配置的集群地址   配置的redis的master和slave的节点地址
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:8001
        - 127.0.0.1:8002
        - 127.0.0.1:8003
    #sentinel:
    #  master: mymaster
    #  nodes:
    #  #哨兵模式配置的集群地址   配置的sentinel的地址
    #    - 127.0.0.1:26379
    #    - 127.0.0.1:26380
    #    - 127.0.0.1:26381



mybatis-plus:
  type-aliases-package: com.redis.bo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl



#redis:
#  password:
#  cluster:
#    #nodes: 10.120.52.38:6300,10.120.52.39:6301,10.120.52.39:6300,10.120.52.40:6301,10.120.52.40:6300,10.120.52.38:6301
#    nodes: 127.0.0.1:6379
#    max-redirects: 5
#  timeout: 60000
#  pool:
#    max-idle: 15
#    max-wait: 60000
#    max-active: 15


