server:
  port: 8000

spring:
  application:
    name: redis
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #datasource:
  #  url: jdbc:mysql://localhost:3306/spring-security?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  #  username: root
  #  password: root
  #  driver-class-name: com.mysql.jdbc.Driver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver   #此处不对哈  mysql驱动包
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    cluster:
      nodes:
        #分片集群配置的集群地址   配置的redis的master和slave的节点地址
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:8001
        - 127.0.0.1:8002
        - 127.0.0.1:8003
    #sentinel:
    #  master: mymaster
    #  nodes:
    #  #哨兵模式配置的集群地址   配置的sentinel的地址
    #    - 127.0.0.1:26379
    #    - 127.0.0.1:26380
    #    - 127.0.0.1:26381

# 可选：设置日志级别，打印更多详细信息
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO


mybatis-plus:
  type-aliases-package: com.redis.dto
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl